version: 0.2

env:
  variables:
    APP_SETTINGS: "config.TestingConfig"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install python-pip python-dev build-essential -y

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase.
  build:
    commands:
      - pip install requirements.txt
      - nose2
  post_build:
    commands:
      - echo Build completed on `date`
